# http://octopress.org/docs/configuring/
# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://fjarcticfox.github.io				# For rewriting urls for RSS, etc
title: 逆水行舟									# Used in the header and title tags
subtitle: Do what you say, say what you do		# A description used in the header
# If your site is a multi-author blog, you may want to set this config's author to the name of your company or project, and add author metadata to posts and pages to give proper attribution for those works.
author: Xiao Longgen							# Your name, for RSS, Copyright, Metadata
simple_search: https://www.google.com/search	# Search engine for simple site search
description: 路漫漫其修远兮，吾将上下而求索			# A default meta description for your site

# Default date format is "ordinal" (resulting in "July 22nd 2007")
# You can customize the format as defined in
# http://www.ruby-doc.org/core-1.9.2/Time.html#method-i-strftime
# Additionally, %o will give you the ordinal representation of the day
date_format: "ordinal"							# Format dates using Ruby's date strftime syntax

# RSS / Email (optional) subscription links (change if using something like Feedburner)
subscribe_rss: /atom.xml						# Url for your blog's feed, defauts to /atom.xml
subscribe_email:								# Url to subscribe by email (service required)
category_feeds: true							# Enable per category RSS feeds (defaults to false in 2.1)
# RSS feeds can list your email address if you like
email: fjarcticfox@gmail.com					# Email address for the RSS feed if you want it.

# http://jekyllrb.com/docs/configuration/
# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# If publishing to a subdirectory as in http://site.com/project set 'root: /project'
root: /											# Mapping for relative urls (default: /)
permalink: /blog/:year/:month/:day/:title/		# Permalink structure for blog posts https://github.com/mojombo/jekyll/wiki/Permalinks
source: source									# Directory for site source files
destination: public								# Directory for generated site files
plugins: plugins								# Directory for Jekyll plugins
code_dir: downloads/code						# Directory for code snippets (for include_code plugin)
category_dir: blog/categories					# Directory for generated blog category pages
markdown: rdiscount
rdiscount:
  extensions:
    - autolink
    - footnotes
    - smart
pygments: false		# default python pygments have been replaced by pygments.rb

paginate: 10          # Posts per page on the blog index
pagination_dir: blog  # Directory base for pagination URLs eg. /blog/page/2/
recent_posts: 5       # Posts in the sidebar Recent Posts section
excerpt_link: "阅读全文 &rarr;"  # "Continue reading" link text at the bottom of excerpted articles

titlecase: true       # Converts page and post titles to titlecase

# list each of the sidebar modules you want to include, in the order you want them to appear.
# To add custom asides, create files in /source/_includes/custom/asides/ and add them to the list like 'custom/asides/custom_aside_name.html'
default_asides: [asides/recent_posts.html, asides/github.html, asides/delicious.html, asides/pinboard.html, asides/googleplus.html]

# Each layout uses the default asides, but they can have their own asides instead. Simply uncomment the lines below
# and add an array with the asides you want to use.
# blog_index_asides:					# Optional sidebar config for blog index page
# post_asides:							# Optional sidebar config for post layout
# page_asides:							# Optional sidebar config for page layout

# http://octopress.org/docs/configuring/
# https://github.com/imathis/octopress/wiki/3rd-party-plugins
# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

# Github repositories
github_user: fjarcticfox
github_repo_count: 0
github_show_profile_link: true
github_skip_forks: true

# Twitter
twitter_user: fjarcticfox
twitter_tweet_button: true

# Google +1
google_plus_one: true
google_plus_one_size: medium

# Google Plus Profile
# Hidden: No visible button, just add author information to search results
googleplus_user: 100396039005337701113
googleplus_hidden: false

# Pinboard https://pinboard.in/
# 网站账户注册需要收费
pinboard_user:
pinboard_count: 3

# Delicious
delicious_user: fjarcticfox
delicious_count: 3

# Disqus Comments
disqus_short_name: fjarcticfox
disqus_show_comment_count: true

# Google Analytics
google_analytics_tracking_id: UA-48617955-1

# Facebook Like
facebook_like: true
